#!/bin/sh

SSH_HOST="$1"

sshrun()
{
    ssh "$SSH_HOST" -- "$@"
}

export PUBKEY=$(echo '{"command": "get_public_key"}' | sudo socat - UNIX-CONNECT:/run/wireguard_peer.sock | jq -r '.data.PublicKey')

jq -cRn '{command: "pair", data: {public_key: env.PUBKEY}}' \
    | sshrun socat - UNIX-CONNECT:/run/wireguard_peer.sock \
    | jq -c '{command: "receive_pair", data: .}' \
    | sudo socat - UNIX-CONNECT:/run/wireguard_peer.sock
