#!/bin/sh

killall backlight_changer
rm /tmp/backlight.fifo
mkfifo -m 600 /tmp/backlight.fifo
tail -f /tmp/backlight.fifo | backlight_changer | wob -t 500 --border-color '#ffffff44' --bar-color '#ffffff44' --background-color '#00000044'
