#!/usr/bin/env python3

from PyQt5.QtWidgets import (
    QApplication,
    QWidget,
    QInputDialog,
)
import sys
import subprocess

class InputEchoer(QWidget):
    def __init__(self):
        super().__init__()
        self.echo_input()
        sys.exit(0)

    def echo_input(self):
        subprocess.run(['killall', 'fcitx5'])
        fcitx5 = subprocess.Popen(['fcitx5'])
        text, ok = QInputDialog.getText(self, 'QT Wayland Input Dialog', '')
        if ok:
            subprocess.run(['wtype', '--', text])
        fcitx5.kill()


def main():
    app = QApplication(sys.argv)
    ie = InputEchoer()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
