#!/bin/sh

gen_random_string()
{
    hexdump -n 16 -e '4/4 "%08x" 1 "\n"' /dev/urandom
}

dir="/run/user/$(id -u)/launcher-comm"
mkdir -p "$dir"

export INPUT_FIFO="$dir/$(gen_random_string).fifo"
export OUTPUT_FIFO="$dir/$(gen_random_string).fifo"
mkfifo -m 600 "$INPUT_FIFO"
mkfifo -m 600 "$OUTPUT_FIFO"

# redirect stdin to $INPUT_FIFO
cat <&0 > "$INPUT_FIFO" &

alacritty \
    --title=launcher \
    -e bash \
    -c 'cat "$INPUT_FIFO" | fzf --ansi --layout=reverse > "$OUTPUT_FIFO"' \
    &

cat "$OUTPUT_FIFO"
rm "$INPUT_FIFO" "$OUTPUT_FIFO"
