#!/usr/bin/fish
# TODO .shell: xwayland or native
swaymsg -t get_tree | jq -c -r '
    ..
    | .nodes?
    | .[]?
    | select(.type | contains("workspace")?)
    | . as $parent
    | ..
    | .nodes?
    | .[]?
    | select(.layout | contains("none"))
    | select(.name | contains("alacritty --title=launcher") | not)
    | (
        if .app_id == null then .window_properties.class
        else .app_id end
    ) as $app
    | (
        if $app == "firefoxdeveloperedition" then ""
        elif $app == "Alacritty" then ""
        elif $app == "Spotify" then ""
        else "" end
    ) as $app_icon
    | ($parent.num|tostring) + "  " + $app_icon + "  " + .name + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t" + $app + "\t" + (.id|tostring)
    '
